# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tx.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08tx.proto\x12\x02tx\"-\n\tTxRequest\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x11\n\tfrom_node\x18\x02 \x01(\t\"7\n\x0cVoteResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x16\n\x04vote\x18\x02 \x01(\x0e\x32\x08.tx.Vote\"6\n\x03\x41\x63k\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1e\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x0c.tx.Decision*9\n\x04Vote\x12\x10\n\x0cVOTE_UNKNOWN\x10\x00\x12\x0f\n\x0bVOTE_COMMIT\x10\x01\x12\x0e\n\nVOTE_ABORT\x10\x02*E\n\x08\x44\x65\x63ision\x12\x14\n\x10\x44\x45\x43ISION_UNKNOWN\x10\x00\x12\x11\n\rGLOBAL_COMMIT\x10\x01\x12\x10\n\x0cGLOBAL_ABORT\x10\x02\x32V\n\x0bParticipant\x12)\n\x04Vote\x12\r.tx.TxRequest\x1a\x10.tx.VoteResponse\"\x00\x12\x1c\n\x06\x44\x65\x63ide\x12\x07.tx.Ack\x1a\x07.tx.Ack\"\x00\x42\x06Z\x04txpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004txpb'
  _globals['_VOTE']._serialized_start=176
  _globals['_VOTE']._serialized_end=233
  _globals['_DECISION']._serialized_start=235
  _globals['_DECISION']._serialized_end=304
  _globals['_TXREQUEST']._serialized_start=16
  _globals['_TXREQUEST']._serialized_end=61
  _globals['_VOTERESPONSE']._serialized_start=63
  _globals['_VOTERESPONSE']._serialized_end=118
  _globals['_ACK']._serialized_start=120
  _globals['_ACK']._serialized_end=174
  _globals['_PARTICIPANT']._serialized_start=306
  _globals['_PARTICIPANT']._serialized_end=392
# @@protoc_insertion_point(module_scope)
