# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft/raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft/raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fraft/raft.proto\x12\x04raft\":\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\"8\n\x12RequestVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\"9\n\x13RequestVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"n\n\x14\x41ppendEntriesRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"O\n\x16\x43lientOperationRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\"M\n\x17\x43lientOperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x11\n\tleader_id\x18\x03 \x01(\t2\xe9\x01\n\x0bRaftService\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12L\n\rClientRequest\x12\x1c.raft.ClientOperationRequest\x1a\x1d.raft.ClientOperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft.raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=25
  _globals['_LOGENTRY']._serialized_end=83
  _globals['_REQUESTVOTEREQUEST']._serialized_start=85
  _globals['_REQUESTVOTEREQUEST']._serialized_end=141
  _globals['_REQUESTVOTERESPONSE']._serialized_start=143
  _globals['_REQUESTVOTERESPONSE']._serialized_end=200
  _globals['_APPENDENTRIESREQUEST']._serialized_start=202
  _globals['_APPENDENTRIESREQUEST']._serialized_end=312
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=314
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=368
  _globals['_CLIENTOPERATIONREQUEST']._serialized_start=370
  _globals['_CLIENTOPERATIONREQUEST']._serialized_end=449
  _globals['_CLIENTOPERATIONRESPONSE']._serialized_start=451
  _globals['_CLIENTOPERATIONRESPONSE']._serialized_end=528
  _globals['_RAFTSERVICE']._serialized_start=531
  _globals['_RAFTSERVICE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
